"""Cryptographically verified trusted-gateway identity.

The internal browser identity headers (``x-milo-auth-user-id`` /
``x-milo-auth-user-email``) are only meaningful when they were generated by
the trusted server-side gateway after it validated the Supabase access
token. Being able to invoke the private Cloud Run service is NOT proof of
that: the worker service account, other internal services, or a
misconfigured IAM binding could also reach it. This module therefore
verifies a separate Google-signed OIDC token presented by the gateway in
the ``X-Milo-Gateway-Token`` header before any identity header is trusted.

Configuration (deliberately separate from worker authentication):

- ``MILO_GATEWAY_AUDIENCE``            audience the gateway mints tokens for;
- ``MILO_APPROVED_GATEWAY_IDENTITIES`` comma-separated service-account
  emails allowed to act as the gateway (must NOT overlap the worker
  allowlist — enforced by backend/production_config.py).

Verified in order: signature (Google certificates), issuer, audience,
expiration, verified service-account email, explicit gateway allowlist.

Modes:

- configured (either variable set): verification is REQUIRED; both
  variables must be present, otherwise every request fails closed (503).
- unconfigured + production: fail closed (503) — production may never fall
  back to bare header trust.
- unconfigured + non-production: development/test mode; header identity is
  accepted so isolated unit tests and local stacks work. The E2E stacks
  configure real (mock-verified) gateway auth instead of relying on this.

A worker identity cannot impersonate a browser user: worker tokens carry
the worker audience and a worker service account, so they fail the
audience check and the gateway allowlist here; conversely gateway
identities are not in the worker allowlist, so they are rejected from
worker mutation routes.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from functools import lru_cache

from fastapi import Depends, Header

from backend.errors import AppError
from backend.worker_auth import GOOGLE_ISSUERS, TokenVerifier

GATEWAY_TOKEN_HEADER = "X-Milo-Gateway-Token"


@dataclass(frozen=True)
class GatewayIdentity:
    service_account_email: str
    audience: str
    issuer: str


class GoogleGatewayTokenVerifier:
    """Production verifier backed by google-auth certificate validation."""

    def verify(self, token: str, audience: str) -> dict:
        import google.auth.transport.requests
        from google.oauth2 import id_token as google_id_token

        request = google.auth.transport.requests.Request()
        return google_id_token.verify_oauth2_token(token, request, audience=audience)


@lru_cache
def get_gateway_token_verifier() -> TokenVerifier:
    return GoogleGatewayTokenVerifier()


def _approved_gateway_identities() -> frozenset[str]:
    raw = os.getenv("MILO_APPROVED_GATEWAY_IDENTITIES", "")
    return frozenset(item.strip().lower() for item in raw.split(",") if item.strip())


def gateway_auth_configured() -> bool:
    return bool(os.getenv("MILO_GATEWAY_AUDIENCE", "").strip()) or bool(_approved_gateway_identities())


def _is_production() -> bool:
    return os.getenv("ENVIRONMENT", "local").strip().lower() == "production"


def verify_gateway_token(token: str | None, verifier: TokenVerifier) -> GatewayIdentity | None:
    """Verify the gateway service token; returns None only in explicit
    non-production development mode with gateway auth unconfigured."""
    audience = os.getenv("MILO_GATEWAY_AUDIENCE", "").strip()
    approved = _approved_gateway_identities()
    if not audience and not approved:
        if _is_production():
            raise AppError("GATEWAY_AUTH_NOT_CONFIGURED", "trusted gateway authentication is not configured", 503)
        return None  # documented non-production development mode
    if not audience or not approved:
        # Partial configuration is always a hard failure: never guess.
        raise AppError("GATEWAY_AUTH_NOT_CONFIGURED", "trusted gateway authentication is not fully configured", 503)
    if not token:
        raise AppError("GATEWAY_AUTH_REQUIRED", "verified gateway identity token is required", 401)
    try:
        claims = verifier.verify(token, audience)
    except Exception as exc:  # signature, expiry, audience, format failures
        raise AppError("GATEWAY_AUTH_INVALID", "gateway identity token rejected", 401) from exc
    issuer = str(claims.get("iss", ""))
    if issuer not in GOOGLE_ISSUERS:
        raise AppError("GATEWAY_AUTH_INVALID", "gateway identity token rejected", 401)
    if str(claims.get("aud", "")) != audience:
        raise AppError("GATEWAY_AUTH_INVALID", "gateway identity token rejected", 401)
    email = str(claims.get("email", "")).strip().lower()
    if not email or claims.get("email_verified") is not True:
        raise AppError("GATEWAY_AUTH_INVALID", "gateway identity token rejected", 401)
    if email not in approved:
        raise AppError("GATEWAY_IDENTITY_NOT_APPROVED", "service identity is not approved to act as the browser gateway", 403)
    return GatewayIdentity(service_account_email=email, audience=audience, issuer=issuer)


def get_verified_gateway(
    x_milo_gateway_token: str | None = Header(default=None),
    verifier: TokenVerifier = Depends(get_gateway_token_verifier),
) -> GatewayIdentity | None:
    return verify_gateway_token(x_milo_gateway_token, verifier)
