"""Verify LIVE Cloud Run service/job configuration against production policy.

This reads the actual `gcloud run services describe --format json` and
`gcloud run jobs describe --format json` output (the LIVE state, not a manifest
generated by the bootstrap) and checks that every required environment
variable, Secret Manager reference, execution flag, budget cap and identity is
correctly configured.

It emits one `STATUS|name|detail` line per finding on stdout, where STATUS is
one of PASS / WARN / BLOCKED / MANUAL / NOT_APPLICABLE, so the caller can fold
the findings into its own structured report. It NEVER prints a secret value —
it only inspects env-var NAMES, secret-reference NAMES and non-secret values.

Exit status is always 0; the findings carry the verdicts.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

EXECUTION_FLAGS = [
    "MILO_ENABLE_RUN_CREATION",
    "MILO_ENABLE_PROPOSAL_MUTATIONS",
    "MILO_ENABLE_PROPOSAL_READS",
    "MILO_ENABLE_RUN_CANCELLATION",
    "MILO_ENABLE_EXECUTION_CONTROL",
    "MILO_ENABLE_PAID_EXECUTION",
]
BUDGETS = [
    "MILO_MAX_COST_PER_RUN",
    "MILO_DAILY_USER_BUDGET",
    "MILO_DAILY_PROJECT_BUDGET",
    "MILO_MAX_MODEL_CALLS_PER_RUN",
    "MILO_MAX_TOTAL_TOKENS_PER_RUN",
    "MILO_MAX_RUN_DURATION_SECONDS",
]

_FINDINGS: list[str] = []


def emit(status: str, name: str, detail: str) -> None:
    # Guard against accidental newlines/pipes corrupting the line protocol.
    detail = detail.replace("\n", " ").replace("|", "/")
    _FINDINGS.append(f"{status}|{name}|{detail}")


def _containers(describe: dict) -> list[dict]:
    """Return the container list from a Cloud Run Service OR Job describe."""
    spec = (((describe or {}).get("spec") or {}).get("template") or {}).get("spec") or {}
    # A Service nests containers directly under template.spec; a Job nests one
    # more ExecutionTemplate level (template.spec.template.spec).
    if "containers" in spec:
        return spec.get("containers") or []
    inner = (spec.get("template") or {}).get("spec") or {}
    return inner.get("containers") or []


def _service_account(describe: dict) -> str:
    spec = (((describe or {}).get("spec") or {}).get("template") or {}).get("spec") or {}
    if "serviceAccountName" in spec:
        return spec.get("serviceAccountName") or ""
    inner = (spec.get("template") or {}).get("spec") or {}
    return inner.get("serviceAccountName") or ""


def _env_maps(describe: dict) -> tuple[dict, dict]:
    """Return (plain_env, secret_refs) as name->value / name->secret-name."""
    plain: dict[str, str] = {}
    secret_ref: dict[str, str] = {}
    for container in _containers(describe):
        for entry in container.get("env") or []:
            name = entry.get("name")
            if not name:
                continue
            if "value" in entry and entry.get("value") is not None:
                plain[name] = str(entry.get("value"))
            vf = entry.get("valueFrom") or {}
            skr = vf.get("secretKeyRef") or {}
            if skr.get("name"):
                secret_ref[name] = str(skr.get("name"))
    return plain, secret_ref


def check_component(label: str, describe: dict, *, expected_sa: str,
                    required_env: list[str], required_flags_false: list[str],
                    required_budgets: list[str], required_secret_refs: dict[str, str],
                    job_launcher_disabled: bool) -> None:
    plain, secret_ref = _env_maps(describe)

    sa = _service_account(describe)
    if not sa:
        emit("BLOCKED", f"live:{label}:sa", f"{label} has no explicit runtime service account (would fall back to the default Compute Engine SA)")
    elif expected_sa and sa != expected_sa:
        emit("BLOCKED", f"live:{label}:sa", f"{label} runs as '{sa}', expected '{expected_sa}'")
    else:
        emit("PASS", f"live:{label}:sa", f"{label} runtime identity is {sa}")

    for name in required_env:
        if name in plain and plain[name].strip():
            emit("PASS", f"live:{label}:env:{name}", f"{name} configured (value not shown)")
        elif name in secret_ref:
            emit("PASS", f"live:{label}:env:{name}", f"{name} configured as a Secret Manager reference")
        else:
            emit("BLOCKED", f"live:{label}:env:{name}", f"required environment variable {name} is not configured on the live {label}")

    if job_launcher_disabled:
        val = plain.get("JOB_LAUNCHER", "")
        if val == "disabled":
            emit("PASS", f"live:{label}:job-launcher", "JOB_LAUNCHER=disabled (Stage A)")
        else:
            emit("BLOCKED", f"live:{label}:job-launcher", f"JOB_LAUNCHER must be 'disabled' for Stage A; found '{val or '(unset)'}'")

    for flag in required_flags_false:
        val = plain.get(flag, "").strip().lower()
        if val in ("false", "0", "no", "off", ""):
            emit("PASS", f"live:{label}:flag:{flag}", f"{flag} is not enabled")
        else:
            emit("BLOCKED", f"live:{label}:flag:{flag}", f"execution flag {flag} is enabled ('{val}'); production must stay execution-disabled")

    # GATEWAY_ALLOW_EXECUTION_ROUTES, if present, must be false.
    gar = plain.get("GATEWAY_ALLOW_EXECUTION_ROUTES", "").strip().lower()
    if gar and gar not in ("false", "0", "no", "off"):
        emit("BLOCKED", f"live:{label}:flag:GATEWAY_ALLOW_EXECUTION_ROUTES", "GATEWAY_ALLOW_EXECUTION_ROUTES must be false")

    for budget in required_budgets:
        val = plain.get(budget, "").strip()
        if not val:
            emit("BLOCKED", f"live:{label}:budget:{budget}", f"budget cap {budget} is not configured on the live {label}")
        else:
            try:
                if float(val) <= 0:
                    raise ValueError
                emit("PASS", f"live:{label}:budget:{budget}", f"{budget}={val} (nonzero)")
            except ValueError:
                emit("BLOCKED", f"live:{label}:budget:{budget}", f"{budget} must be a nonzero numeric cap; found '{val}'")

    for env_name, secret_name in required_secret_refs.items():
        actual = secret_ref.get(env_name, "")
        if not actual:
            emit("BLOCKED", f"live:{label}:secret-ref:{env_name}", f"{env_name} is not wired to a Secret Manager reference on the live {label}")
        elif secret_name and actual != secret_name:
            emit("BLOCKED", f"live:{label}:secret-ref:{env_name}", f"{env_name} references secret '{actual}', expected '{secret_name}'")
        else:
            emit("PASS", f"live:{label}:secret-ref:{env_name}", f"{env_name} references Secret Manager resource {actual}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--service-json", required=True)
    p.add_argument("--job-json", required=True)
    p.add_argument("--expected-api-sa", default="")
    p.add_argument("--expected-worker-sa", default="")
    p.add_argument("--supabase-url-secret", required=True)
    p.add_argument("--supabase-key-secret", required=True)
    p.add_argument("--provider-secret", required=True)
    p.add_argument("--redis-secret", required=True)
    args = p.parse_args()

    def load(path: str):
        try:
            return json.loads(Path(path).read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None

    svc = load(args.service_json)
    job = load(args.job_json)

    if svc is None:
        emit("MANUAL", "live:api", "could not read a valid Cloud Run API service description; verify the live API configuration manually")
    else:
        check_component(
            "api", svc, expected_sa=args.expected_api_sa,
            required_env=[
                "ENVIRONMENT", "ALLOWED_CORS_ORIGINS", "MILO_GATEWAY_AUDIENCE",
                "MILO_APPROVED_GATEWAY_IDENTITIES", "MILO_APPROVED_WORKER_IDENTITIES",
                "UPSTASH_REDIS_REST_URL",
            ],
            required_flags_false=EXECUTION_FLAGS,
            required_budgets=BUDGETS,
            required_secret_refs={
                "SUPABASE_URL": args.supabase_url_secret,
                "SUPABASE_SECRET_KEY": args.supabase_key_secret,
                "UPSTASH_REDIS_REST_TOKEN": args.redis_secret,
            },
            job_launcher_disabled=True,
        )

    if job is None:
        emit("MANUAL", "live:worker", "could not read a valid Cloud Run worker job description; verify the live worker configuration manually")
    else:
        check_component(
            "worker", job, expected_sa=args.expected_worker_sa,
            required_env=[
                "ENVIRONMENT", "MILO_WORKER_AUDIENCE",
                "MILO_APPROVED_WORKER_IDENTITIES", "UPSTASH_REDIS_REST_URL",
            ],
            required_flags_false=EXECUTION_FLAGS,
            required_budgets=BUDGETS,
            required_secret_refs={
                "SUPABASE_URL": args.supabase_url_secret,
                "SUPABASE_SECRET_KEY": args.supabase_key_secret,
                "KIMI_API_KEY": args.provider_secret,
                "UPSTASH_REDIS_REST_TOKEN": args.redis_secret,
            },
            job_launcher_disabled=False,
        )

    # Identity separation on the live resources.
    if svc is not None and job is not None:
        api_sa = _service_account(svc)
        worker_sa = _service_account(job)
        if api_sa and worker_sa and api_sa == worker_sa:
            emit("BLOCKED", "live:shared-identity", "live API service and worker job share a runtime identity; they must be distinct")
        elif api_sa and worker_sa:
            emit("PASS", "live:distinct-identity", "live API and worker run as distinct service accounts")

    for line in _FINDINGS:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
