'use client';
import { useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { useRunRealtime } from '@/lib/useRunRealtime';
import { AgentState, InternetPolicy, Proposal, SourceRecord } from '@/lib/types';
import { redactSecrets, safeText, safeUrl } from '@/lib/sanitize';
const internetLabels: InternetPolicy[] = ['forbidden','allowed','required','conditional','requested','approved','denied','active'];
export default function WorkspacePage(){ const [mobileOpen,setMobileOpen]=useState(false); const [request,setRequest]=useState('Research a market with verifiable sources.'); const [proposal,setProposal]=useState<Proposal>(); const [conversationId,setConversationId]=useState(''); const [runId,setRunId]=useState(''); const [tab,setTab]=useState('Agents'); const {state,mode}=useRunRealtime(runId); const agents=Object.values(state.agents); const elapsed=useMemo(()=>state.run?.started_at?Math.round((Date.now()-Date.parse(state.run.started_at))/1000):0,[state.run?.started_at,state.events.length]);
async function propose(){ setProposal(await api.createProposal(request)); } async function start(){ const run=await api.startRun(conversationId, request, { proposal_id: proposal?.id }); setRunId(run.run_id); } async function cancel(){ if(runId) await api.cancel(runId,'User cancelled from workspace'); }
return <main className="shell"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}>☰ Workspace</button><aside className={`sidebar ${mobileOpen?'open':''}`}><button className="close" onClick={()=>setMobileOpen(false)}>×</button><h1>MILO</h1><button className="primary">+ New project</button><input aria-label="Search projects" placeholder="Search projects or conversations"/><section><h2>Projects</h2>{['Market research','Vehicle catalog','Due diligence'].map((p,i)=><div className="nav-card" key={p}><span>{p}</span>{i===0&&<b className="pulse">run active</b>}</div>)}</section><section><h2>Conversations</h2><div className="nav-card active">Realtime workspace</div><input value={conversationId} onChange={e=>setConversationId(e.target.value)} placeholder="Conversation UUID" aria-label="Conversation UUID"/></section></aside><section className="chat"><header><div><p className="eyebrow">Backend-authoritative agent workspace</p><h2>Professional realtime run console</h2></div><span className={`badge ${mode}`}>{mode} • refresh-safe</span></header><div className="messages"><article className="message user"><b>User request</b><textarea value={request} onChange={e=>setRequest(e.target.value)} aria-label="User request"/><button onClick={propose}>Create workflow proposal</button></article>{proposal&&<ProposalCard proposal={proposal} onApprove={()=>api.decideProposal(proposal.id,'approve','Approved in UI').then(setProposal)} onReject={()=>api.decideProposal(proposal.id,'reject','Rejected in UI').then(setProposal)} onRevise={()=>api.reviseProposal(proposal.id,request).then(setProposal)} onStart={start}/>}<RunCard status={state.run?.status??(runId?'running':'idle')} elapsed={elapsed} progress={state.progress} agents={agents} sources={state.sources.length} conflicts={state.conflicts.length} tokens={state.tokens} cost={state.cost} phase={state.currentPhase}/><article className="message assistant"><b>Live event stream</b>{state.events.length===0?<p>No events yet. Browser close will not stop backend runs; paste a run ID to reconnect.</p>:state.events.map(e=><div className="event" key={e.id}><span>{e.created_at?.slice(11,19)}</span><b>{e.event_type}</b><em>{e.agent}</em><p>{safeText(e.message)}</p></div>)}<input placeholder="Instruction during run (sent as metadata in next backend endpoint)" aria-label="User instruction during run"/><div><button>Retry</button><button>Resume</button><button onClick={cancel}>Cancel</button></div></article><article className="artifacts"><b>Final artifacts</b><pre>{JSON.stringify(redactSecrets(state.run?.output ?? {}),null,2)}</pre></article></div></section><aside className="inspector"><nav>{['Agents','Workflow','Sources','Claims','Conflicts','Costs','Developer'].map(t=><button className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><Inspector tab={tab} agents={agents} state={state}/></aside></main> }
function ProposalCard({proposal,onApprove,onReject,onRevise,onStart}:any){return <article className="proposal"><h3>Workflow proposal</h3><p>Status: <b>{proposal.status}</b></p><div className="grid"><pre>{JSON.stringify(proposal.task_spec,null,2)}</pre><pre>{JSON.stringify(proposal.estimates,null,2)}</pre></div><button onClick={onApprove}>Approve</button><button onClick={onReject}>Reject</button><button onClick={onRevise}>Revise</button><button className="primary" onClick={onStart}>Start run</button></article>}
function RunCard(p:any){return <article className="run-card"><h3>Live run</h3><div className="progress"><span style={{width:`${p.progress}%`}}/></div><dl>{Object.entries({status:p.status,elapsed:`${p.elapsed}s`,progress:`${p.progress}%`,agents:`${p.agents.filter((a:AgentState)=>a.status==='active').length} active / ${p.agents.filter((a:AgentState)=>a.status==='completed').length} done / ${p.agents.filter((a:AgentState)=>a.status==='failed').length} failed`,sources:p.sources,conflicts:p.conflicts,tokens:p.tokens,cost:`$${p.cost.toFixed?.(4)??p.cost}`,phase:p.phase,background:'running server-side'}).map(([k,v])=><><dt>{k}</dt><dd>{String(v)}</dd></>)}</dl></article>}
function AgentCard({a}:{a:AgentState}){return <div className="agent-card"><h4>{a.name}</h4><p>{a.responsibility}</p><InternetBadge policy={a.internet} reason={a.internetReason} quota={a.quota} domains={a.domains}/><p>{a.status} • {a.progress}% • {a.currentTask}</p><small>{a.searchesUsed} searches • {a.sources.length} sources • {a.tokens} tokens • ${a.cost.toFixed(4)} • {a.retries} retries • {a.fallbacks.join(', ')}</small></div>}
function InternetBadge({policy,reason,quota,domains}:any){return <span className={`internet ${policy}`}>{policy} internet — {reason||'policy visible'} {quota&&`quota ${quota}`} {domains?.length?`domains ${domains.join(',')}`:''}</span>}
function Source({s}:{s:SourceRecord}){const url=safeUrl(s.url); return <div className="source"><b>{url?<a href={url} rel="noreferrer" target="_blank">{safeText(s.title)}</a>:safeText(s.title)}</b><p>{s.domain} • {s.source_type}/{s.source_strength} • date {s.source_date||'n/a'} • retrieved {s.retrieved_at}</p><small>{s.agent} • {s.query} • {s.tool_operation} • claims {(s.claims||[]).join(', ')}</small></div>}
function Inspector({tab,agents,state}:any){ if(tab==='Agents') return <>{agents.map((a:AgentState)=><AgentCard key={a.name} a={a}/>)}{internetLabels.map(p=><InternetBadge key={p} policy={p}/>)}</>; if(tab==='Workflow') return <div className="timeline">{state.events.map((e:any)=><p key={e.id}>↳ {e.phase||e.event_type}: dependencies, active path, failures/partial, dynamic agents, supervisor decisions</p>)}</div>; if(tab==='Sources') return <>{state.sources.map((s:SourceRecord)=><Source key={s.id} s={s}/>)}</>; if(tab==='Claims') return <pre>{JSON.stringify(state.claims,null,2)}</pre>; if(tab==='Conflicts') return <pre>{JSON.stringify(state.conflicts,null,2)}</pre>; if(tab==='Costs') return <pre>{JSON.stringify({tokens:state.tokens,cost:state.cost,agents:agents.map((a:AgentState)=>({name:a.name,tokens:a.tokens,cost:a.cost}))},null,2)}</pre>; return <pre>{JSON.stringify(redactSecrets({events:state.events,WorkflowSpec:state.run?.output,AgentSpecs:agents,SupervisorCommands:state.supervisor,validationErrors:state.validationErrors,retries:agents.map((a:AgentState)=>a.retries),checkpoints:state.checkpoints,structuredRawErrors:state.rawErrors}),null,2)}</pre> }
