substitutions:
  _WORKER_IMAGE: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.worker
      - --tag
      - ${_WORKER_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_WORKER_IMAGE}

images:
  - ${_WORKER_IMAGE}
