substitutions:
  _API_IMAGE: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.api
      - --tag
      - ${_API_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_API_IMAGE}

images:
  - ${_API_IMAGE}
