-- Exact confirmed legacy production baseline: the four tables that exist in
-- production Supabase before any migration (001-006) has ever been applied.
-- Used by tests/test_migrations_postgres.py to validate that migrations
-- 001-006 upgrade this baseline in place without losing data.
--
-- Every column, type, NOT NULL, default, identity, CHECK (including
-- constraint names), foreign-key delete behavior, non-primary index, and
-- RLS flag below was confirmed against the actual production schema.
-- Nothing here is inferred or approximated: if a property was not
-- explicitly confirmed, it is not asserted by this fixture.

create extension if not exists pgcrypto;

create table public.conversations (
  id uuid not null primary key default gen_random_uuid(),
  title text not null default 'שיחה חדשה',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.conversations enable row level security;

create table public.runs (
  id uuid not null primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_prompt text not null,
  status text not null default 'queued'
    constraint runs_status_check check (status = any (array['queued', 'running', 'completed', 'failed', 'cancelled'])),
  current_phase text,
  progress integer not null default 0
    constraint runs_progress_check check (progress >= 0 and progress <= 100),
  cancel_requested boolean not null default false,
  result jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);
alter table public.runs enable row level security;
create index runs_conversation_id_idx on public.runs(conversation_id);
create index runs_status_idx on public.runs(status);

create table public.messages (
  id bigint not null generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  run_id uuid references public.runs(id) on delete set null,
  sender_role text not null check (sender_role in ('user', 'assistant', 'system', 'tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.messages enable row level security;
create index messages_conversation_id_created_at_idx on public.messages(conversation_id, created_at);

create table public.run_events (
  id bigint not null generated by default as identity primary key,
  run_id uuid not null references public.runs(id) on delete cascade,
  event_type text not null,
  agent_name text,
  message text,
  progress integer check (progress >= 0 and progress <= 100),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.run_events enable row level security;
create index run_events_run_id_created_at_idx on public.run_events(run_id, created_at);
