-- Exact confirmed legacy production baseline: the four tables that exist in
-- production Supabase before any migration (001-006) has ever been applied.
-- Used by tests/test_migrations_postgres.py to validate that migrations
-- 001-006 upgrade this baseline in place without losing data.

create extension if not exists pgcrypto;

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  title text,
  created_at timestamptz not null default now()
);

create table public.runs (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.conversations(id),
  user_prompt text not null,
  status text,
  current_phase text,
  progress integer,
  cancel_requested boolean default false,
  result jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.conversations(id),
  run_id uuid references public.runs(id),
  sender_role text not null check (sender_role in ('user', 'assistant', 'system')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.run_events (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.runs(id) on delete cascade,
  agent_name text,
  progress integer check (progress >= 0 and progress <= 100),
  message text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
