-- Exact confirmed legacy production baseline: the four tables that exist in
-- production Supabase before any migration (001-006) has ever been applied.
-- Used by tests/test_migrations_postgres.py to validate that migrations
-- 001-006 upgrade this baseline in place without losing data.
--
-- Every column, type, NOT NULL, default, identity, CHECK, foreign-key
-- delete behavior, and RLS flag below was confirmed against the actual
-- production schema. No index beyond each table's primary key is asserted
-- here, because no other index was confirmed; migrations 001-006 create
-- their own indexes independently of this fixture.

create extension if not exists pgcrypto;

create table public.conversations (
  id uuid not null primary key default gen_random_uuid(),
  title text not null default 'שיחה חדשה',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.conversations enable row level security;

create table public.runs (
  id uuid not null primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id),
  user_prompt text not null,
  status text not null default 'queued',
  current_phase text,
  progress integer not null default 0,
  cancel_requested boolean not null default false,
  result jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);
alter table public.runs enable row level security;

create table public.messages (
  id bigint not null generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  run_id uuid references public.runs(id) on delete set null,
  sender_role text not null check (sender_role in ('user', 'assistant', 'system', 'tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.messages enable row level security;

create table public.run_events (
  id bigint not null generated by default as identity primary key,
  run_id uuid not null references public.runs(id) on delete cascade,
  event_type text not null,
  agent_name text,
  message text,
  progress integer check (progress >= 0 and progress <= 100),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.run_events enable row level security;
